import Head from 'next/head';
import { useState } from 'react';
import { CountryCard, Footer, SearchBar } from '../components';

// style
import styles from '../styles/Home.module.scss';
import { motion } from 'framer-motion';
import { Link } from 'next/link';

export default function Home({ data }) {
  const [searchInput, setSearchInput] = useState('');

  const searchInputHandle = (e) => setSearchInput(e.target.value);

  const printData = data.filter((c) => c.name.toLowerCase().includes(searchInput));

  const contries = {
    hidden: { opacity: 0 },
    show: { opacity: 1, transition: { type: 'spring', staggerChildren: 0.1, duration: 0.5 } },
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SearchBar searchInputHandle={searchInputHandle} />
        <div className={styles.cardContainer}>
          <motion.ul variants={contries} initial="hidden" animate="show">
            {printData.map((country, i) => (
              <CountryCard key={`key${i}`} country={country} />
            ))}
          </motion.ul>
        </div>
      </main>

      <Footer />
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch('https://restcountries.com/v2/all');

  const data = await res.json();

  return { props: { data: data } };
};
